export interface LinkItem {
    name: string;
    url: string;
    icon?: string;
    description?: string;
}

export interface CategoryData {
    title: string;
    kanji: string;
    romaji: string;
    tagline: string;
    icon: string;
    links: LinkItem[];
}

const bulletIcon = "/icons/torrents.jpg";

export const categoryLinks: Record<string, CategoryData> = {
    favorites: {
        title: "Favorites",
        kanji: "星",
        romaji: "Favorites / Bookmarks",
        tagline: "Your starred links & custom personal bookmarks",
        icon: "/icons/favorites.jpg",
        links: [],
    },
    movies: {
        title: "Movies & TV",
        kanji: "映画",
        romaji: "Eiga / Cinema",
        tagline: "High-definition cinema streaming & TV archives",
        icon: "/icons/movies.jpg",
        links: [
            { name: "Soap2Night", url: "https://hokejatv.com/movies.html", icon: bulletIcon },
            { name: "LookMovie", url: "https://www.lookmovie2.to/", icon: bulletIcon },
            { name: "Cineby", url: "https://www.cineby.gd/", icon: bulletIcon },
            { name: "DoraWatch", url: "https://dorawatch.one/home/", icon: bulletIcon },
            { name: "HydraHD", url: "https://hydrahd.ru/", icon: bulletIcon },
            { name: "Cinema.bz", url: "https://cinema.bz/", icon: bulletIcon },
            { name: "Goojara", url: "https://ww1.goojara.to/", icon: bulletIcon },
            { name: "Mapple", url: "https://mapple.mov/", icon: bulletIcon },
            { name: "PressPlay", url: "https://pressplay.top/", icon: bulletIcon },
            { name: "NunFlix", url: "https://nunflix.li/", icon: bulletIcon },
            { name: "RidoMovies", url: "https://ridomovies.tv/", icon: bulletIcon },
            { name: "123MoviesFree", url: "https://ww7.123moviesfree.net/home/", icon: bulletIcon },
            { name: "VidPlay", url: "https://vidplay.top/", icon: bulletIcon },
            { name: "YesMovies", url: "https://ww.yesmovies.ag/", icon: bulletIcon },
            { name: "PrimeWire", url: "https://www.primewire.mov/home", icon: bulletIcon },
            { name: "ramoflix.net", url: "https://ramoflix.net/", icon: bulletIcon },
            { name: "wmovies.org", url: "https://wmovies.org/", icon: bulletIcon },
            { name: "doraby.com", url: "https://doraby.com/", icon: bulletIcon },
            { name: "hydrahd.ws", url: "https://hydrahd.ws/", icon: bulletIcon },
            { name: "7movies.in", url: "https://7movies.in/", icon: bulletIcon },
            { name: "aether.ist", url: "https://aether.ist/", icon: bulletIcon },
            { name: "fluxtv.cc", url: "https://fluxtv.cc/", icon: bulletIcon },
            { name: "streamvaults.ru", url: "https://streamvaults.ru/", icon: bulletIcon },
            { name: "primeshows.org", url: "https://primeshows.org/", icon: bulletIcon },
            { name: "67movies.net", url: "https://67movies.net/", icon: bulletIcon },
            { name: "shuttletv.su", url: "https://shuttletv.su/", icon: bulletIcon },
            { name: "popcornmovies.ac", url: "https://popcornmovies.ac/", icon: bulletIcon },
            { name: "stellar.gdn", url: "https://stellar.gdn/", icon: bulletIcon },
            { name: "onionplay.st", url: "https://onionplay.st/", icon: bulletIcon },
            { name: "pressplayz.to", url: "https://pressplayz.to/", icon: bulletIcon },
            { name: "nepu.io", url: "https://nepu.io/", icon: bulletIcon },
            { name: "soap2dayhd.net", url: "https://soap2dayhd.net/", icon: bulletIcon },
            { name: "azmovies.to", url: "https://azmovies.to/", icon: bulletIcon },
            { name: "mapple.club", url: "https://mapple.club/", icon: bulletIcon },
            { name: "opstream.fun", url: "https://opstream.fun/", icon: bulletIcon },
            { name: "latestmovies.net", url: "https://latestmovies.net/", icon: bulletIcon },
            { name: "officialmoviebox.com", url: "https://officialmoviebox.com/", icon: bulletIcon },
            { name: "hdtoday24.at", url: "https://hdtoday24.at/", icon: bulletIcon },
            { name: "cinebytv.com", url: "https://cinebytv.com/", icon: bulletIcon },
            { name: "ridomovies.su", url: "https://ridomovies.su/", icon: bulletIcon },
            { name: "123moviesfree.net", url: "https://123moviesfree.net/", icon: bulletIcon },
            { name: "willowmovies.com", url: "https://willowmovies.com/", icon: bulletIcon },
            { name: "cinemaos.live", url: "https://cinemaos.live/", icon: bulletIcon },
            { name: "anixtv.us.cc", url: "https://anixtv.us.cc/", icon: bulletIcon },
            { name: "moviepire.ru", url: "https://moviepire.ru/", icon: bulletIcon },
            { name: "flicker-mini.pages.dev", url: "https://flicker-mini.pages.dev/", icon: bulletIcon },
            { name: "m4uhd.page", url: "https://m4uhd.page/", icon: bulletIcon },
        ],
    },
    anime: {
        title: "Anime",
        kanji: "アニメ",
        romaji: "Anime / Broadcast",
        tagline: "Seasonal anime broadcasts, streams & raw releases",
        icon: "/icons/anime.jpg",
        links: [
            { name: "anime.nexus", url: "https://anime.nexus/", icon: bulletIcon },
            { name: "miruro.to", url: "https://www.miruro.to/", icon: bulletIcon },
            { name: "9animetv.to", url: "https://9animetv.to/", icon: bulletIcon },
            { name: "anitaku.io", url: "https://anitaku.io/", icon: bulletIcon },
            { name: "gogoanime.org.vc", url: "https://wvv.gogoanime.org.vc/", icon: bulletIcon },
            { name: "animepahe.ru", url: "https://animepahe.ru/", icon: bulletIcon },
            { name: "animension.to", url: "https://animension.to/", icon: bulletIcon },
            { name: "kaido.to", url: "https://kaido.to/", icon: bulletIcon },
            { name: "marin.moe", url: "https://marin.moe/", icon: bulletIcon },
            { name: "anisuge.tv", url: "https://anisuge.tv/", icon: bulletIcon },
            { name: "anizone.to", url: "https://anizone.to/", icon: bulletIcon },
            { name: "animepahe.pw", url: "https://animepahe.pw/", icon: bulletIcon },
            { name: "anify.to", url: "https://anify.to/", icon: bulletIcon },
            { name: "yenime.net", url: "https://yenime.net/", icon: bulletIcon },
            { name: "kickass-anime.ro", url: "https://kickass-anime.ro/", icon: bulletIcon },
            { name: "animex.one", url: "https://animex.one/", icon: bulletIcon },
            { name: "animegg.org", url: "https://animegg.org/", icon: bulletIcon },
            { name: "animestream.net", url: "https://animestream.net/", icon: bulletIcon },
            { name: "kissanime.com.ru", url: "https://kissanime.com.ru/", icon: bulletIcon },
            { name: "allmanga.to", url: "https://allmanga.to/", icon: bulletIcon },
            { name: "aniworld.to", url: "https://aniworld.to/", icon: bulletIcon },
            { name: "wcostream.tv", url: "https://wcostream.tv/", icon: bulletIcon },
            { name: "justanime.to", url: "https://justanime.to/", icon: bulletIcon },
            { name: "123animes.ru", url: "https://123animes.ru/", icon: bulletIcon },
        ],
    },
    torrents: {
        title: "Torrents",
        kanji: "急流",
        romaji: "Kyūryū / P2P Swarm",
        tagline: "Decentralized P2P swarms, indexers & trackers",
        icon: "/icons/torrents.jpg",
        links: [
            { name: "Nyaa.si", url: "https://nyaa.si/", icon: bulletIcon },
            { name: "LimeTorrents", url: "https://www.limetorrents.lol/", icon: bulletIcon },
            { name: "SubsPlease", url: "https://subsplease.org/", icon: bulletIcon },
            { name: "limetorrents.fun", url: "https://limetorrents.fun/", icon: bulletIcon },
            { name: "yts.bz", url: "https://yts.bz/", icon: bulletIcon },
            { name: "eztvx.to", url: "https://eztvx.to/", icon: bulletIcon },
            { name: "torrentgalaxy.one", url: "https://torrentgalaxy.one/", icon: bulletIcon },
            { name: "extratorrent.st", url: "https://extratorrent.st/", icon: bulletIcon },
        ],
    },
    manga: {
        title: "Manga & Comics",
        kanji: "漫画",
        romaji: "Manga / Archives",
        tagline: "Scans, webtoons, light novels & raw archives",
        icon: "/icons/manga.jpg",
        links: [
            { name: "MangaFire", url: "https://mangafire.to/", icon: bulletIcon },
            { name: "MangaReader", url: "https://mangareader.to/", icon: bulletIcon },
            { name: "Asura Scans", url: "https://asuracomic.net/", icon: bulletIcon },
            { name: "Flame Comics", url: "https://flamecomics.xyz/", icon: bulletIcon },
            { name: "comix.to", url: "https://comix.to/", icon: bulletIcon },
            { name: "mangahaven.net", url: "https://mangahaven.net/", icon: bulletIcon },
            { name: "mangataro.org", url: "https://mangataro.org/", icon: bulletIcon },
            { name: "allmanga.to", url: "https://allmanga.to/", icon: bulletIcon },
            { name: "mangago.me", url: "https://mangago.me/", icon: bulletIcon },
            { name: "weebcentral.com", url: "https://weebcentral.com/", icon: bulletIcon },
            { name: "manganato.gg", url: "https://manganato.gg/", icon: bulletIcon },
            { name: "kagane.org", url: "https://kagane.org/", icon: bulletIcon },
        ],
    },
    comics: {
        title: "Comics",
        kanji: "🦸",
        romaji: "Comics / Graphic Archives",
        tagline: "Digital comics, public-domain issues & graphic archives",
        icon: "https://i.pinimg.com/736x/a2/f8/bf/a2f8bf57d72adeb1d27cb5a21db7758a.jpg",
        links: [
            { name: "globalcomix.com", url: "https://globalcomix.com/", icon: bulletIcon },
            { name: "xoxocomic.com", url: "https://xoxocomic.com/", icon: bulletIcon },
            { name: "comicbookplus.com", url: "https://comicbookplus.com/", icon: bulletIcon },
            { name: "batcave.biz", url: "https://batcave.biz/", icon: bulletIcon },
            { name: "getcomics.org", url: "https://getcomics.org/", icon: bulletIcon },
        ],
    },
    piracy: {
        title: "Piracy Mega",
        kanji: "海賊",
        romaji: "Kaizoku / Vault",
        tagline: "FMHY, community vaults & mega resources",
        icon: "/icons/piracy.jpg",
        links: [
            { name: "FMHY Wiki", url: "https://fmhy.net/", icon: bulletIcon },
            { name: "Piracy Megathread", url: "https://rentry.co/megathread", icon: bulletIcon },
            { name: "Champagne Piracy Directory", url: "https://champagne.pages.dev/", icon: bulletIcon },
            { name: "Ripper Store", url: "https://ripper.store/", icon: bulletIcon },
        ],
    },
    software: {
        title: "Software",
        kanji: "電脳",
        romaji: "Dennō / Programs",
        tagline: "Repacks, open-source utilities & developer kits",
        icon: "/icons/software.jpg",
        links: [
            { name: "Massgrave (MAS)", url: "https://massgrave.dev/", icon: bulletIcon },
            { name: "FileCR", url: "https://filecr.com/en/", icon: bulletIcon },
            { name: "FMHY Software Vault", url: "https://fmhy.net/system-tools", icon: bulletIcon },
        ],
    },
    games: {
        title: "Games",
        kanji: "遊戯",
        romaji: "Yūgi / Game Hub",
        tagline: "Scene releases, repacks, ROMs & emulators",
        icon: "/icons/games.jpg",
        links: [
            { name: "DODI Repacks", url: "https://dodi-repacks.site/", icon: bulletIcon },
            { name: "SteamRIP", url: "https://steamrip.com/", icon: bulletIcon },
            { name: "GOG Games", url: "https://gog-games.to/", icon: bulletIcon },
            { name: "OnlineFix", url: "https://online-fix.me/", icon: bulletIcon },
            { name: "Vimm's Lair", url: "https://vimm.net/", icon: bulletIcon },
            { name: "CS.RIN.RU", url: "https://cs.rin.ru/forum/", icon: bulletIcon },
            { name: "ankergames.net", url: "https://ankergames.net/", icon: bulletIcon },
            { name: "g4u.to", url: "https://g4u.to/", icon: bulletIcon },
            { name: "steamgg.net", url: "https://steamgg.net/", icon: bulletIcon },
            { name: "m4ckd0ge-repacks.site", url: "https://m4ckd0ge-repacks.site/", icon: bulletIcon },
            { name: "gload.to", url: "https://gload.to/", icon: bulletIcon },
        ],
    },
    music: {
        title: "Music & Audio",
        kanji: "音楽",
        romaji: "Ongaku / Sonic",
        tagline: "Lossless FLAC, streaming & discographies",
        icon: "/icons/music.jpg",
        links: [
            { name: "DoubleDouble", url: "https://doubledouble.top/", icon: bulletIcon },
            { name: "spotdownloader.com", url: "https://spotdownloader.com/", icon: bulletIcon },
            { name: "spotifymate.com", url: "https://spotifymate.com/", icon: bulletIcon },
            { name: "spotmate.online", url: "https://spotmate.online/", icon: bulletIcon },
            { name: "racoon", url: "https://shailendramaurya.github.io/racoon/", icon: bulletIcon },
            { name: "ytiz.xyz", url: "https://ytiz.xyz/", icon: bulletIcon },
            { name: "lucida.to", url: "https://lucida.to/", icon: bulletIcon },
            { name: "cobalt.tools", url: "https://cobalt.tools/", icon: bulletIcon },
            { name: "slsknet.org", url: "https://slsknet.org/", icon: bulletIcon },
            { name: "github.io/downline", url: "https://balkarjun.github.io/downline/", icon: bulletIcon },
        ],
    },
    books: {
        title: "Books & Papers",
        kanji: "書籍",
        romaji: "Shoseki / Library",
        tagline: "Academic journals, textbooks, EPUBs & audiobooks",
        icon: "/icons/books.jpg",
        links: [
            { name: "AudiobookBay", url: "https://audiobookbay.lu/", icon: bulletIcon },
            { name: "z-lib.gd", url: "https://z-lib.gd/", icon: bulletIcon },
            { name: "fulllengthaudiobooks.com", url: "https://fulllengthaudiobooks.com/", icon: bulletIcon },
            { name: "foxit.com", url: "https://www.foxit.com/", icon: bulletIcon },
            { name: "flowoss.com", url: "https://flowoss.com/", icon: bulletIcon },
        ],
    },
    "asian-drama": {
        title: "Asian Drama",
        kanji: "韓劇",
        romaji: "K-Drama / Asian Cinema",
        tagline: "Korean drama broadcasts, historical sagas & Asian cinema",
        icon: "/icons/asian-drama.jpg",
        links: [
            { name: "asiaflix.net", url: "https://asiaflix.net/home", icon: bulletIcon },
            { name: "kisskh.id", url: "https://kisskh.id/", icon: bulletIcon },
            { name: "kissasian.com.lv", url: "https://ww14.kissasian.com.lv/", icon: bulletIcon },
            { name: "dramacool.com.tr", url: "https://dramacool.com.tr/", icon: bulletIcon },
            { name: "myasiantv.com.bz", url: "https://myasiantv.com.bz/", icon: bulletIcon },
            { name: "kisskh.club", url: "https://kisskh.club/", icon: bulletIcon },
        ],
    },
    adblockers: {
        title: "AdBlockers",
        kanji: "🛡️",
        romaji: "AdBlock / Privacy",
        tagline: "Block intrusive ads, pop-ups & malicious scripts",
        icon: "https://i.pinimg.com/736x/08/5e/78/085e78f4d07b5443fcb74ca318a4674b.jpg",
        links: [
            { name: "Opera Browser", url: "https://www.opera.com/", icon: bulletIcon },
            { name: "uBlock Origin", url: "https://ublockorigin.com/", icon: bulletIcon },
            { name: "AdBlock Plus", url: "https://adblockplus.org/", icon: bulletIcon },
            { name: "AdGuard", url: "https://adguard.com/", icon: bulletIcon },
            { name: "AdBlock", url: "https://getadblock.com/", icon: bulletIcon },
            { name: "Poper Blocker", url: "https://poperblocker.com/", icon: bulletIcon },
        ],
    },
    vpn: {
        title: "VPN",
        kanji: "🔒",
        romaji: "VPN / Private Relay",
        tagline: "Privacy-focused VPN services and secure browsing",
        icon: "https://i.pinimg.com/736x/04/61/fc/0461fc5dae4d7a344541fbd8199f13f8.jpg",
        links: [
            { name: "Proton VPN", url: "https://protonvpn.com/", icon: bulletIcon },
            { name: "Surfshark VPN", url: "https://surfshark.com/", icon: bulletIcon },
            { name: "ExpressVPN", url: "https://www.expressvpn.com/", icon: bulletIcon },
            { name: "CyberGhost VPN", url: "https://www.cyberghostvpn.com/", icon: bulletIcon },
            { name: "Private Internet Access VPN", url: "https://www.privateinternetaccess.com/", icon: bulletIcon },
            { name: "VeePN", url: "https://veepn.com/", icon: bulletIcon },
        ],
    },
    streaming: {
        title: "Live TV & Sports",
        kanji: "放送",
        romaji: "Hōsō / Relay",
        tagline: "Live global television networks & sports streams",
        icon: "/icons/streaming.jpg",
        links: [
            { name: "StreamEast", url: "https://streameast.gd/", icon: bulletIcon },
            { name: "TheTVApp", url: "https://thetvapp.to/", icon: bulletIcon },
            { name: "Sportsurge", url: "https://sportsurge.net/", icon: bulletIcon },
            { name: "IPTV-Org", url: "https://iptv-org.github.io/", icon: bulletIcon },
            { name: "fctv33.hair", url: "https://fctv33.hair/", icon: bulletIcon },
            { name: "bintv.cc", url: "https://bintv.cc/", icon: bulletIcon },
            { name: "sportyhunter.xyz", url: "https://sportyhunter.xyz/", icon: bulletIcon },
            { name: "crackstreams.io", url: "https://crackstreams.io/", icon: bulletIcon },
            { name: "score808hd.tv", url: "https://score808hd.tv/", icon: bulletIcon },
            { name: "timstreams.st", url: "https://timstreams.st/", icon: bulletIcon },
            { name: "globetv.app", url: "https://globetv.app/", icon: bulletIcon },
            { name: "daddylive.st", url: "https://daddylive.st/", icon: bulletIcon },
            { name: "tv247us.live", url: "https://tv247us.live/", icon: bulletIcon },
            { name: "publiciptv.com", url: "https://publiciptv.com/", icon: bulletIcon },
        ],
    },
    design: {
        title: "Art & Assets",
        kanji: "美術",
        romaji: "Bijutsu / Studio",
        tagline: "Wallpapers, vectors, 3D models & sound effects",
        icon: "/icons/design.jpg",
        links: [
            { name: "Wallhaven", url: "https://wallhaven.cc/", icon: bulletIcon },
            { name: "Freesound", url: "https://freesound.org/", icon: bulletIcon },
            { name: "Kenney Assets", url: "https://kenney.nl/assets", icon: bulletIcon },
            { name: "Poly Pizza", url: "https://poly.pizza/", icon: bulletIcon },
        ],
    },
    tools: {
        title: "Web Tools",
        kanji: "道具",
        romaji: "Dōgu / Toolkit",
        tagline: "Cobalt downloaders, link sanitizers & DNS testers",
        icon: "/icons/tools.jpg",
        links: [
            { name: "Cobalt.tools", url: "https://cobalt.tools/", icon: bulletIcon },
            { name: "CyberChef", url: "https://gchq.github.io/CyberChef/", icon: bulletIcon },
            { name: "Temp-Mail", url: "https://temp-mail.org/", icon: bulletIcon },
            { name: "File.io", url: "https://www.file.io/", icon: bulletIcon },
            { name: "WebTorrent IO", url: "https://webtorrent.io/", icon: bulletIcon },
        ],
    },
};
